
import {
  Root,
  App,
  RootText,
  Widget,
  ImageBase,
  WindowBase,
  WindowManager,
  CanvasWidget,
  ColorComponent,
  ColorPicker,
  Draggable,
  FileBrowserView,
  GaugePointer,
  Gauge,
  ImageAnimation,
  ImageValue,
  Candidates,
  LangIndicator,
  LineNumber,
  Mledit,
  ProgressCircle,
  RichTextView,
  RichText,
  HscrollLabel,
  ListItem,
  ListViewH,
  ListView,
  ScrollBar,
  ScrollView,
  SlideMenu,
  SlideIndicator,
  SlideView,
  Switch,
  TextSelector,
  TimeClock,
  Vpage,
  AppBar,
  ButtonGroup,
  Button,
  CheckButton,
  ClipView,
  ColorTile,
  Column,
  ComboBoxItem,
  DialogClient,
  DialogTitle,
  DigitClock,
  Dragger,
  Edit,
  GridItem,
  Grid,
  GroupBox,
  Label,
  Pages,
  ProgressBar,
  Row,
  Slider,
  TabButtonGroup,
  TabButton,
  TabControl,
  View,
  Dialog,
  Window,
  GifImage,
  Keyboard,
  MutableImage,
  SvgImage,
  CalibrationWin,
  ComboBox,
  Image,
  Overlay,
  Popup,
  SpinBox,
  SystemBar,
  ComboBoxEx,
      
} from "../components/";
    
    // Creates an element with an element type, props and a root instance
function createElement(type: string, props: any): any {
  const COMPONENTS = { 
    APP: () => App(props),
    ROOT: () => Root(props),
    ROOTTEXT: () => RootText(props),
    WIDGET: () => Widget(props),
    IMAGEBASE: () => ImageBase(props),
    WINDOWBASE: () => WindowBase(props),
    WINDOWMANAGER: () => WindowManager(props),
    CANVASWIDGET: () => CanvasWidget(props),
    COLORCOMPONENT: () => ColorComponent(props),
    COLORPICKER: () => ColorPicker(props),
    DRAGGABLE: () => Draggable(props),
    FILEBROWSERVIEW: () => FileBrowserView(props),
    GAUGEPOINTER: () => GaugePointer(props),
    GAUGE: () => Gauge(props),
    IMAGEANIMATION: () => ImageAnimation(props),
    IMAGEVALUE: () => ImageValue(props),
    CANDIDATES: () => Candidates(props),
    LANGINDICATOR: () => LangIndicator(props),
    LINENUMBER: () => LineNumber(props),
    MLEDIT: () => Mledit(props),
    PROGRESSCIRCLE: () => ProgressCircle(props),
    RICHTEXTVIEW: () => RichTextView(props),
    RICHTEXT: () => RichText(props),
    HSCROLLLABEL: () => HscrollLabel(props),
    LISTITEM: () => ListItem(props),
    LISTVIEWH: () => ListViewH(props),
    LISTVIEW: () => ListView(props),
    SCROLLBAR: () => ScrollBar(props),
    SCROLLVIEW: () => ScrollView(props),
    SLIDEMENU: () => SlideMenu(props),
    SLIDEINDICATOR: () => SlideIndicator(props),
    SLIDEVIEW: () => SlideView(props),
    SWITCH: () => Switch(props),
    TEXTSELECTOR: () => TextSelector(props),
    TIMECLOCK: () => TimeClock(props),
    VPAGE: () => Vpage(props),
    APPBAR: () => AppBar(props),
    BUTTONGROUP: () => ButtonGroup(props),
    BUTTON: () => Button(props),
    CHECKBUTTON: () => CheckButton(props),
    CLIPVIEW: () => ClipView(props),
    COLORTILE: () => ColorTile(props),
    COLUMN: () => Column(props),
    COMBOBOXITEM: () => ComboBoxItem(props),
    DIALOGCLIENT: () => DialogClient(props),
    DIALOGTITLE: () => DialogTitle(props),
    DIGITCLOCK: () => DigitClock(props),
    DRAGGER: () => Dragger(props),
    EDIT: () => Edit(props),
    GRIDITEM: () => GridItem(props),
    GRID: () => Grid(props),
    GROUPBOX: () => GroupBox(props),
    LABEL: () => Label(props),
    PAGES: () => Pages(props),
    PROGRESSBAR: () => ProgressBar(props),
    ROW: () => Row(props),
    SLIDER: () => Slider(props),
    TABBUTTONGROUP: () => TabButtonGroup(props),
    TABBUTTON: () => TabButton(props),
    TABCONTROL: () => TabControl(props),
    VIEW: () => View(props),
    DIALOG: () => Dialog(props),
    WINDOW: () => Window(props),
    GIFIMAGE: () => GifImage(props),
    KEYBOARD: () => Keyboard(props),
    MUTABLEIMAGE: () => MutableImage(props),
    SVGIMAGE: () => SvgImage(props),
    CALIBRATIONWIN: () => CalibrationWin(props),
    COMBOBOX: () => ComboBox(props),
    IMAGE: () => Image(props),
    OVERLAY: () => Overlay(props),
    POPUP: () => Popup(props),
    SPINBOX: () => SpinBox(props),
    SYSTEMBAR: () => SystemBar(props),
    COMBOBOXEX: () => ComboBoxEx(props),

    default: undefined
  };  
  return (COMPONENTS as any)[type]() || COMPONENTS.default;
}
    
export { createElement };
